services:
  db:
    image: mysql:9.2.0
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: paynest
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db

  redis:
    image: redis:7.4.1-alpine3.20
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:RELEASE.2025-05-24T17-08-30Z-cpuv1
    container_name: 'minio'
    ports:
      - ":9000:9000"
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      # MINIO_DEFAULT_BUCKETS: fileStorage
    restart: 'no'
    command: server /data --console-address ":9001"
    volumes:
      - minio_project_data:/data
volumes:
  db_data:
  minio_project_data: