services:
  db:
    image: mysql:9.2.0
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: paynest
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db

  redis:
    image: redis:7.4.1-alpine3.20
    ports:
      - "6379:6379"


volumes:
  db_data: